/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TullingGest;

import java.time.LocalDate;
import java.time.Month;
import java.util.HashSet;
import java.util.Set;

import org.junit.Test;

import TullingGest.classes.dao.AdminDAO;
import TullingGest.classes.dao.FamiliaDAO;
import TullingGest.classes.entity.Admin;
import TullingGest.classes.entity.Endereco;
import TullingGest.classes.entity.Familia;
import TullingGest.classes.entity.MembroDaFamilia;
import TullingGest.classes.entity.Pessoa;
import TullingGest.enums.TipoDeMembro;

public class AppTest {

    @Test
    public void testFamiliaCanBeSaved() {

        var admin = new Admin("Nkrumah Alípio", "nkrumah@admin.com", "12345678");
        (new AdminDAO()).save(admin);
        var pai = new Pessoa("Nkrumah Alípio", "944540733", "nkrumah2000@gmail.com", LocalDate.of(2000, Month.MAY, 19),
                TipoDeMembro.Pai, "ronaldinho");
        var mae = new Pessoa("Nauria Jorge", "949120192", "nauriaj@gmail.com", LocalDate.of(2000, Month.OCTOBER, 25),
                TipoDeMembro.Mãe, "ronaldinho");
        Set<MembroDaFamilia> membros = new HashSet<MembroDaFamilia>();
        membros.add(pai);
        membros.add(mae);
        var endereco = new Endereco("Benfica", "Salinas");
        var familia = new Familia("Aliuria", "912345678", membros, endereco);
        (new FamiliaDAO()).save(familia);

    }
}